0:OK
1:You are not authorized.
2:Incorrect username/password.
3:The server is busy with another provider.
4:You must first remove children.
5:Could not find the nodes to reorder.
6:Could not open this file for writing.
Not a document.
8:Could not write web.
9:Could not find a node.
10:The file path is incorrect.
11:Item already exists.
12:Could not locate the source.
13:Server did not understand the request.
14:This version not found.
15:Could not find server file.
The requested file cannot be accessed.
The requested file is a directory.
18:The destination file is a directory.
19:This is a public node.
20:Unknown output format type.
21:This function has been disabled.
22:Text search failed.
23:More nodes to go, continue.
